### ISSUE TITLE
End positions are off by 1

### ISSUE THREAD

**Issue by gregokent** [dominikh/go-structlayout#5]
The default output when running the example is 

```
$ structlayout bufio Reader
Reader.buf []byte: 0-24 (24 bytes)
Reader.rd io.Reader: 24-40 (16 bytes)
Reader.r int: 40-48 (8 bytes)
Reader.w int: 48-56 (8 bytes)
Reader.err error: 56-72 (16 bytes)
Reader.lastByte int: 72-80 (8 bytes)
Reader.lastRuneSize int: 80-88 (8 bytes)
```

but the end positions are all off by 1 when starting with a 0-index.

Should be something like 

```
$ structlayout bufio Reader
Reader.buf []byte: 0-23 (size 24, align 8)
Reader.rd io.Reader: 24-39 (size 16, align 8)
Reader.r int: 40-47 (size 8, align 8)
Reader.w int: 48-55 (size 8, align 8)
Reader.err error: 56-71 (size 16, align 8)
Reader.lastByte int: 72-79 (size 8, align 8)
Reader.lastRuneSize int: 80-87 (size 8, align 8)
```

**Comment by dominikh** [comment]
It's a half-open interval `[start,end)`. This way of representing it was chosen because a byte occupies a space of length one. A single byte thus extends from position 0 to position 1, which makes a lot more sense than it extending from position 0 to position 0.

**Comment by gregokent** [comment]
I understand what you intend, but the way it is currently output, e.g. 0-24, implies to me the byte range 0 through 24, meaning the first byte in the range starts at offset 0 and the last byte in the range starts at offset 24.

**Comment by dominikh** [comment]
I don't think there is one right answer here. When I've chosen the current format, I asked people and they preferred the current format. Different people will have different interpretations, and one group of people will have to adapt, I'm afraid.

If it helps with adapting, consider slicing a `[]byte` (that represents the struct data) in Go: `b[0:1]` will get you one byte, not two.

I'm sorry that this inconveniences you, but I don't think we'll change anything here.

**Comment by gregokent** [comment]
No worries, I appreciate you taking the time for the explanations
