### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Dieterbe** [dominikh/go-structlayout#6]
Hey Dominik!
in the master checkout of https://github.com/raintank/raintank-metric/tree/master/metric_tank
I get this:

```
~/g/s/g/r/r/metric_tank > structlayout . Req
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x401412]

goroutine 1 [running]:
panic(0x69a1a0, 0xc820010160)
    /home/dieter/code/go/src/runtime/panic.go:464 +0x3e6
main.main()
    /home/dieter/go/src/honnef.co/go/structlayout/cmd/structlayout/main.go:48 +0x3b2
```

i'm probably invoking it wrong (i also tried 'main' instead of . ), but still a nilpointer shouldn't happen :)

**Comment by dominikh** [comment]
The correct invocation at the moment is `structlayout github.com/raintank/raintank-metric/metric_tank Req` – but you're right that the panic should be fixed (and the usage message improved). Eventually we'll support relative package paths, too.

**Comment by dmitshur** [comment]
I'll just leave this here in case it's helpful:

``` Go
pkg = relativeToAbsoluteImportPath(flag.Args()[0])

func relativeToAbsoluteImportPath(importPath string) {
    wd, err := os.Getwd()
    if err != nil {
        return "", err
    }
    bpkg, err := build.Import(importPath, wd, 0) // Or build.ImportComment if you want.
    if err != nil {
        return "", err
    }
    return bpkg.ImportPath, nil
}
```

The only thing I'm not sure is the naming/terminology. Relative import path is okay. But what's the other one. Absolute? Full? There's also the distinction of including /vendor/ left intact and with it stripped out... What to call those...

**Comment by dominikh** [comment]
@shurcooL I already have code for this, which is used in other tools (such as `unused`). It's called `resolveRelative` there, which does an in-place replace on a list of paths, and also takes care of `.go` arguments.

This tool is special, because in the future it will also accept file names and positions in those files, so you can specify a struct type by offset. That's why it doesn't support relative paths yet.

**Comment by dominikh** [comment]
Migrated to https://github.com/dominikh/go-tools/issues/182.
